### ISSUE TITLE
SIGSEGV when deleting copied profile

### ISSUE THREAD

**Issue by frickler24** [mattanger/ckb-next#38] opened 2017-01-21 22:49 UTC
This Issue is for me to remember. But if someone is faster than me :-)
Scenario is as follows:
1. open ckb
2. duplicate one of the profiles on the left (tested with KB K95RGB)
3. delete the **upper** one of the two siblings
4. crash.
Crash-protocol from gdb ist here:
[Absturz-beim-Profillöschen.txt](https://github.com/mattanger/ckb-next/files/721552/Absturz-beim-Profilloschen.txt)
It is reproducable an error (nil-ptr) somewhere in the button-handler (action).

**Comment by tatokis** [comment] 2017-01-21 22:58
While trying to reproduce yours, I stumbled upon another SIGSEGV.

All I did was go to "manage profiles" and then right click -> duplicate the first profile.
```
(gdb) bt
#0  0x00007ffff6a50de0 in qHash(QUuid const&, unsigned int) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x0000000000451fdb in QHash<QUuid, AnimScript*>::findNode(QUuid const&, unsigned int*) const ()
#2  0x000000000044a7fb in AnimScript::copy(QObject*, QUuid const&) ()
#3  0x00000000004550b4 in KbAnim::KbAnim(QObject*, KeyMap const&, KbAnim const&) ()
#4  0x000000000044010e in KbLight::KbLight(KbMode*, KeyMap const&, KbLight const&) ()
[...]
```

**Comment by frickler24** [comment] 2017-01-22 08:27
@tatokis I tried a bit to produce your error but I couldn't produce it.
Is the first profile you try to duplicate marked as "saved to HW"? How many profiles do you have?
Anyhow, I'll have a look at it when debugging. Thanks!
@mattanger could you plz mark this issue as a bug?

**Comment by frickler24** [comment] 2017-02-11 22:53
@tatokis I've found the reason for the bug as I described it. 
Despite a lot of tests, I could not reproduce the behavior your mentioned above.
Do you have any more hints?

**Comment by ghost** [comment] 2017-02-26 16:50
@tatokis I wasn't able to reproduce it on Ubuntu 16.10 with different combinations (saved into HW, not saved etc.).
However, I managed to reproduce this one by @frickler24. Will try a patch from a new PR.

UPD. the patch worked for me. I still wasn't able to reproduce your case.

**Comment by ghost** [comment] 2017-03-04 01:28
I have no idea why it didn't close the issue, maybe it closes it only when the header contains a notice and not the body, or because I force pushed a few times (sorry).

**Closed as completed by ghost** 2017-03-04 01:28 UTC
Labels: bug, resolved
