### ISSUE TITLE
QuickInstall script throws an error

### ISSUE THREAD

**Issue by kunalkapoor** [mattanger/ckb-next#250] opened 2017-07-07 18:25 UTC
Quickinstall script fails for my on Mac Sierra 10.12.3. Not sure where the failure is so I pasted a verbose log below.

# Devices information

ckb-dev-report info:

```
$> cat ckb-dev-detect-report

ckb-dev-detect - Fri Jul  7 13:21:07 CDT 2017

Kernel: Darwin kunalk-m01 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

OS Version:
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32

USB Devices:
            Corsair Gaming K70 LUX RGB Keyboard :

              Product ID: 0x1b33
              Vendor ID: 0x1b1c  (CORSAIR MEMORY INC.)
              Version: 2.05
              Serial Number: 1403D025AEBD15015627CF43F5001943
              Speed: Up to 12 Mb/sec
              Manufacturer: Corsair
              Location ID: 0x14420000 / 4
              Current Available (mA): 500
              Current Required (mA): 500
              Extra Operating Current (mA): 0
```

---

# Steps

Git cloned ckb repo "master" branch. Ran the quickinstall script.

```
clangclang: error: clang: error: : invalid version number in '-mmacosx-version-min='clangclanginvalid version number in '-mmacosx-version-min='error: 
: : error: error
invalid version number in '-mmacosx-version-min='invalid version number in '-mmacosx-version-min='

: invalid version number in '-mmacosx-version-min='
make[2]: *** [debug/main.o] Error 1
make[2]: *** [debug/main.o] Error 1make[2]: *** [debug/main.o] Error 1make[2]: *** [debug/main.o] Error 1

make[2]: *** [debug/main.o] Error 1

make[1]: *** [debug] Error 2
make[1]: *** [debug] Error 2
make[1]: *** [debug] Error 2
make[1]: *** [debug] Error 2
make: *** [sub-src-ckb-pinwheel-make_first] Error 2
make: *** Waiting for unfinished jobs....
make: *** [sub-src-ckb-random-make_first] Error 2
make: *** [sub-src-ckb-wave-make_first] Error 2
make[1]: *** [debug] Error 2
make: *** [sub-src-ckb-ripple-make_first] Error 2
make: *** [sub-src-ckb-gradient-make_first] Error 2
clang: error: invalid version number in '-mmacosx-version-min='
make[2]: *** [debug/main.o] Error 1
make[1]: *** [debug] Error 2
make: *** [sub-src-ckb-rain-make_first] Error 2
clang: error: invalid version number in '-mmacosx-version-min='
make[2]: *** [debug/device.o] Error 1
make[2]: *** Waiting for unfinished jobs....
clang: error: invalid version number in '-mmacosx-version-min='clang: error: invalid version number in '-mmacosx-version-min='
clang: error: 
invalid version number in '-mmacosx-version-min='
clang: error: invalid version number in '-mmacosx-version-min='
clang: error: invalid version number in '-mmacosx-version-min='
make[2]: *** [debug/input_linux.o] Error 1
make[2]: *** [debug/input.o] Error 1
make[2]: *** [debug/input_mac.o] Error 1
make[2]: *** [debug/devnode.o] Error 1
make[2]: *** [debug/main.o] Error 1
clang: error: invalid version number in '-mmacosx-version-min='
make[2]: *** [debug/notify.o] Error 1
make[1]: *** [debug] Error 2
make: *** [sub-src-ckb-daemon-make_first] Error 2
rebindwidget.ui: Warning: The name 'layoutWidget' (QWidget) is already in use, defaulting to 'layoutWidget2'.
In file included from settingswidget.cpp:5:
In file included from ./kb.h:7In file included from kblight.cpp:5:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from mainwindow.cpp:2:
In file included from ./kbmanager.h:8:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from kbwidget.cpp:7:
In file included from ./fwupgradedialog.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from main.cpp:1:
In file included from ./mainwindow.h:9:
In file included from ./kbwidget.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
settingswidget.cpp:143:47: warning: unused parameter 'index' [-Wunused-parameter]
void SettingsWidget::on_capsBox_activated(int index){
                                              ^
settingswidget.cpp:147:48: warning: unused parameter 'index' [-Wunused-parameter]
void SettingsWidget::on_shiftBox_activated(int index){
                                               ^
settingswidget.cpp:151:47: warning: unused parameter 'index' [-Wunused-parameter]
void SettingsWidget::on_ctrlBox_activated(int index){
                                              ^
settingswidget.cpp:155:46: warning: unused parameter 'index' [-Wunused-parameter]
void SettingsWidget::on_altBox_activated(int index){
                                             ^
settingswidget.cpp:159:46: warning: unused parameter 'index' [-Wunused-parameter]
void SettingsWidget::on_winBox_activated(int index){
                                             ^
2 warnings generated.
kbwidget.cpp:168:91: warning: unused parameter 'previous' [-Wunused-parameter]
void KbWidget::on_modesList_currentItemChanged(QListWidgetItem *current, QListWidgetItem *previous){
                                                                                          ^
mainwindow.cpp:257:64: warning: unused parameter 'reason' [-Wunused-parameter]
void MainWindow::iconClicked(QSystemTrayIcon::ActivationReason reason){
                                                               ^
2 warnings generated.
7 warnings generated.
In file included from kbprofile.cpp:1:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
kbanim.cpp:333:32: warning: unused parameter 'bg' [-Wunused-parameter]
static float blendNormal(float bg, float fg){
                               ^
3 warnings generated.
3 warnings generated.
kbanimwidget.cpp:151:94: warning: unused parameter 'previous' [-Wunused-parameter]
void KbAnimWidget::on_animList_currentItemChanged(QListWidgetItem *current, QListWidgetItem *previous){
                                                                                             ^
animadddialog.cpp:28:46: warning: unused parameter 'index' [-Wunused-parameter]
void AnimAddDialog::on_animBox_activated(int index){
                                             ^
animsettingdialog.cpp:487:57: warning: unused parameter 'arg1' [-Wunused-parameter]
void AnimSettingDialog::on_delayBox_valueChanged(double arg1){
                                                        ^
animsettingdialog.cpp:491:58: warning: unused parameter 'arg1' [-Wunused-parameter]
void AnimSettingDialog::on_repeatBox_valueChanged(double arg1){
                                                         ^
animsettingdialog.cpp:495:59: warning: unused parameter 'arg1' [-Wunused-parameter]
void AnimSettingDialog::on_kpDelayBox_valueChanged(double arg1){
                                                          ^
animsettingdialog.cpp:499:60: warning: unused parameter 'arg1' [-Wunused-parameter]
void AnimSettingDialog::on_kpRepeatBox_valueChanged(double arg1){
                                                           ^
animsettingdialog.cpp:503:58: warning: unused parameter 'arg1' [-Wunused-parameter]
void AnimSettingDialog::on_kpReleaseBox_stateChanged(int arg1){
                                                         ^
1 warning generated.
1 warning generated.
1 warning generated.
gradientdialog.cpp:174:98: warning: unused parameter 'previous' [-Wunused-parameter]
void GradientDialog::on_presetList_currentItemChanged(QListWidgetItem *current, QListWidgetItem *previous){
                                                                                                 ^
gradientdialog.cpp:240:54: warning: unused parameter 'arg1' [-Wunused-parameter]
void GradientDialog::on_stopOpacity_valueChanged(int arg1){
                                                     ^
In file included from kbmode.cpp:1:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from kb.cpp:6:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
5 warnings generated.
rlistwidget.cpp:54:43: warning: unused parameter 'item' [-Wunused-parameter]
void RListWidget::change(QListWidgetItem* item){
                                          ^
2 warnings generated.
1 warning generated.
In file included from kbprofiledialog.cpp:2:
In file included from ./kbprofiledialog.h:5:
In file included from ./kbwidget.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from keywidget.cpp:7:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
kbprofiledialog.cpp:39:100: warning: unused parameter 'previous' [-Wunused-parameter]
void KbProfileDialog::on_profileList_currentItemChanged(QListWidgetItem *current, QListWidgetItem *previous){
                                                                                                   ^
In file included from kbbindwidget.cpp:2:
In file included from ./kbbindwidget.h:5:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from kbbind.cpp:4:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from rebindwidget.cpp:2:
In file included from ./rebindwidget.h:5:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
3 warnings generated.
In file included from modeselectdialog.cpp:1:
In file included from ./modeselectdialog.h:5:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
rebindwidget.cpp:850:48: warning: unused parameter 'checked' [-Wunused-parameter]
void RebindWidget::on_rb_delay_no_toggled(bool checked)
                                               ^
rebindwidget.cpp:862:53: warning: unused parameter 'checked' [-Wunused-parameter]
void RebindWidget::on_rb_delay_asTyped_toggled(bool checked)
                                                    ^
rebindwidget.cpp:873:53: warning: unused parameter 'checked' [-Wunused-parameter]
void RebindWidget::on_rb_delay_default_toggled(bool checked)
                                                    ^
2 warnings generated.
2 warnings generated.
2 warnings generated.
2 warnings generated.
2 warnings generated.
In file included from kbfirmware.cpp:1:
In file included from ./kbfirmware.h:4:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from kbperf.cpp:2:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from fwupgradedialog.cpp:3:
In file included from ./fwupgradedialog.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
kbperf.cpp:330:27: warning: comparison of constant 8 with expression of type 'KbPerf::indicator' is always false [-Wtautological-constant-out-of-range-compare]
    if(index < 0 || index >= I_COUNT)
                    ~~~~~ ^  ~~~~~~~
kbperf.cpp:345:27: warning: comparison of constant 8 with expression of type 'KbPerf::indicator' is always false [-Wtautological-constant-out-of-range-compare]
    if(index < 0 || index >= I_COUNT)
                    ~~~~~ ^  ~~~~~~~
5 warnings generated.
In file included from keyaction.cpp:2:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
4 warnings generated.
In file included from mperfwidget.cpp:1:
In file included from ./mperfwidget.h:11:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from kperfwidget.cpp:1:
In file included from ./kperfwidget.h:9:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from mperfwidget.cpp:81layoutdialog.cpp:2:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
:36: warning: unused parameter 'index' [-Wunused-parameter]
void MPerfWidget::colorClicked(int index){
                                   ^
2 warnings generated.
2 warnings generated.
2 warnings generated.
In file included from extrasettingswidget.cpp:3:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from kbmanager.cpp:1:
In file included from ./kbmanager.h:8:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
3 warnings generated.
2 warnings generated.
2 warnings generated.
In file included from release/moc_kbprofile.cpp:9:
In file included from release/../kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_mainwindow.cpp:9:
In file included from release/../mainwindow.h:9:
In file included from ./kbwidget.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_kbwidget.cpp:9:
In file included from release/../kbwidget.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
2 warnings generated.
In file included from release/moc_kbmode.cpp:9:
In file included from release/../kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from release/moc_kb.cpp:9:
In file included from release/../kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from release/moc_kbbind.cpp:9:
In file included from release/../kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_kbbindwidget.cpp:9:
In file included from release/../kbbindwidget.h:5:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_kbprofiledialog.cpp:9:
In file included from release/../kbprofiledialog.h:5:
In file included from ./kbwidget.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from release/moc_rebindwidget.cpp:9:
In file included from release/../rebindwidget.h:5:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_modeselectdialog.cpp:9:
In file included from release/../modeselectdialog.h:5:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
2 warnings generated.
2 warnings generated.
In file included from release/moc_keyaction.cpp:9:
release/../keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
release/../keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from release/moc_kbfirmware.cpp:9:
In file included from release/../kbfirmware.h:4:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_fwupgradedialog.cpp:9:
In file included from release/../fwupgradedialog.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from release/moc_mperfwidget.cpp:9:
In file included from release/../mperfwidget.h:11:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_kperfwidget.cpp:9:
In file included from release/../kperfwidget.h:9:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from release/moc_kbmanager.cpp:9:
In file included from release/../kbmanager.h:8:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.

Press enter to exit.```

**Comment by ashtonium** [comment] 2017-07-08 16:42
I also have a similar problem

**Comment by ghost** [comment] 2017-07-08 22:10
Duplicate of #232.

**Closed as completed by ghost** 2017-07-08 22:10 UTC
Labels: duplicate
