### ISSUE TITLE
New Mouse - Corsair CH-9301011-EU Harpoon

### ISSUE THREAD

**Issue by ghost** [mattanger/ckb-next#85] opened 2017-02-26 00:16 UTC
Hi, just a request from me. Just wondered if you guys could add a new mouse to the software (Corsair CH-9301011-EU Harpoon). Anyway, if you can or can't thanks anyway really love the software :)
If I can help in any way, please ask and I will.

**Comment by ghost** [comment] 2017-02-26 00:52
Hey. Run the `ckb-dev-detect` from the source code tree and upload the output. I suppose you're on Linux.

**Comment by ghost** [comment] 2017-03-16 16:40
And if you're on macOS, then now you can provide the info following the instructions in #31 (see my last comment there, at the end).

**Comment by tatokis** [comment] 2017-04-25 11:29
Duplicate of #54.

**Closed as completed by tatokis** 2017-04-25 11:29 UTC
Labels: duplicate, enhancement
