### ISSUE TITLE
Profile corruption

### ISSUE THREAD

**Issue by tbcrawford-old** [mattanger/ckb-next#83] opened 2017-02-23 16:29 UTC
My color profiles were available last time I was logged into my computer. This morning when I turned my computer on, the `ckb Demo` profile was missing from ckb-next. I was wondering where these profiles get stored so that I may be able to look into this myself some if anyone has this knowledge. I am on macOS.

I also wanted to report this as a possible issue of the profile(s) not being loaded properly. Though I believe this is a **_rare bug_**. 

I managed to get the `ckb Demo` profile back by commenting out code in `src/ckb/kb.cpp` one time and running the quick installation.

I am looking at the following lines: [kb.cpp L258](https://github.com/mattanger/ckb-next/blob/master/src/ckb/kb.cpp#L258)
```c++
if(newCurrentProfile)
    setCurrentProfile(newCurrentProfile);
else {
    // If nothing was loaded, load the demo profile
    QSettings demoSettings(":/txt/demoprofile.conf", QSettings::IniFormat, this);
    CkbSettings cSettings(demoSettings);
    KbProfile* demo = new KbProfile(this, getKeyMap(), cSettings, "{BA7FC152-2D51-4C26-A7A6-A036CC93D924}");
    _profiles.append(demo);
    setCurrentProfile(demo);
}
```

and changing it to the following and running ckb-next one time:
```c++
// if(newCurrentProfile)
    // setCurrentProfile(newCurrentProfile);
// else {
    // If nothing was loaded, load the demo profile
    QSettings demoSettings(":/txt/demoprofile.conf", QSettings::IniFormat, this);
    CkbSettings cSettings(demoSettings);
    KbProfile* demo = new KbProfile(this, getKeyMap(), cSettings, "{BA7FC152-2D51-4C26-A7A6-A036CC93D924}");
    _profiles.append(demo);
    setCurrentProfile(demo);
// }
```

After seeing that the profile came back properly, you'll want to uninstall ckb-next. Reset the ckb-next back to what it previously was in the code and then run the quick installation again.

**Comment by frickler24** [comment] 2017-02-23 21:24
@tbcrawford Would it be an idea to put this change as a new CLI parameter ("--restore-std-profiles")? 
Do you want to implement this change completely (incl help, documentation, README.md-update, ...) as a pullrequest?
What do our maintainers think about it?

**Comment by tatokis** [comment] 2017-02-23 21:28
From what I can see, commenting the code above will cause ckb-next to reload the demo profile from the resources and write it to disk on every launch, meaning it will overwrite any local modifications to it.
I am afraid this is not a solution.
I also don't think adding a CLI parameter to restore the profile is a good idea.

Instead, we need to find out the root cause for the profile corruption, fix it, and then once the import/export system is implemented, we can just provide the default one as a download, or even better, just make a button in the GUI to reset everything.

**Comment by tbcrawford-old** [comment] 2017-02-23 21:29
I see your point @tatokis. But yes, it will overwrite any modifications. I am just trying to get the default profile back as I lost any profiles I previously had. This is a work around however. Deeming it a solution is a bit poor on my side I concede. 

The workaround works by uninstall ckb-next, making this small workaround in the code, getting the profiles back after installing ckb-next, uninstalling ckb-next again, reverting the code back to how it was originally, and then installing ckb-next once again from the current source.

**Comment by ghost** [comment] 2017-02-23 23:08
I will support @tatokis and Eric Raymond:
> The net benefit of having anything that can be called a software development methodology is in inverse proportion to the quality of your developers – and possibly inverse-squared.

We demonstrate even more incompetence than we have now by creating more crutches. Don't take it personally.

And yes, the button "Unfuck plz" is a good idea. Very good idea.

**Comment by frickler24** [comment] 2017-02-27 18:02
@tbcrawford any idea, how you lost your profile information?
If not, we should close this issue.

**Comment by tbcrawford-old** [comment] 2017-02-27 18:23
@frickler24 I wish I had some clue, but I do not. I just recall this happening before for some reason too. I went ahead and closed it.

**Comment by ghost** [comment] 2017-04-04 00:13
This seems to be related to #113 and #128.

**Comment by frickler24** [comment] 2017-04-08 09:58
I'm wondering that all three issues are related to macOS. Is there a special treatment for the mechnism used to handle the profile info? It is a very simple qt mechanism, which does an abstraction on linux conf-files, windows registry and a mac function (I do not know the last one).  So are there known bugs for this function?

**Comment by ghost** [comment] 2017-05-03 20:53
Here's a fixed bug from Qt tracker: [QSetting setValue("", float) does not work for all Qt apps running on iOS 10 and macOS Sierra](https://bugreports.qt.io/browse/QTBUG-56124) and here's another one being marked as duplicate, reported a bit later: [QSettings serialization problems on Mac](https://bugreports.qt.io/browse/QTBUG-56565). Please, take a look. It might be related to our problem. It was fixed (or at least the developers say so) in `5.7.1` and `5.8`.

**Comment by frickler24** [comment] 2017-05-03 21:53
Maybe #174 can help to gather more info?

**Closed as completed** 2018-01-21 20:26 UTC
Labels: bug, macOS, migration
