### ISSUE TITLE
Firmware update not working

### ISSUE THREAD

**Issue by OSCrustacean** [mattanger/ckb-next#379] opened 2018-01-13 02:18 UTC
I am currently using Fedora 27. I have the K70 RGB RAPIDFIRE keyboard and it says that I have to upgrade the firmware to v2.05. When I click upgrade the popup appears, and I click start. Immediately it says update failed.

**Comment by Ravenslofty** [comment] 2018-01-13 09:01
Dupe of #328 and #97. Will be fixed when #220 is merged.

This bug occurs because the GUI doesn't distinguish between a K70 and a K70 LUX.

**Closed as completed** 2018-01-13 10:41 UTC
Labels: duplicate
