### ISSUE TITLE
quick install errors

### ISSUE THREAD

**Issue by ashtonium** [mattanger/ckb-next#251] opened 2017-07-08 16:51 UTC
---

# New device support request

- [ ] Yes
- [x] No

<sub><sup>leave empty if you have no new device support requests</sup></sub>

You should upload:
* __Linux__: `ckb-dev-detect-report.gz` is enough
* __macOS__: a full dump following [the instructions](https://github.com/mattanger/ckb-next/issues/31#issuecomment-285380447)

---

# Feature request

- [ ] Yes
- [x] No

<sub><sup>leave empty if you have no feature requests</sup></sub>

## Any other notes & comments?

---

# Bug report

- [x] Yes
- [x] No

<sub><sup>leave empty if you have no bug reports</sup></sub>

## General information
The quick install script doesn't install properly and gives me a lot of errors
### Source
(how and where did you get this program, e.g.: _"`ckb-next-git` package in AUR"_ or _"built manually using quickinstall script"_ or _"pkg for macOS"_)
quick install script
### Branch
(fill in if ckb-next was compiled manually, e.g.: _"master"_ or _"newdev"_)
master i think
## Logs & crash reports
(any useful information - an OS crash report, debugger's backtrace, any non-standard way of usage (BIOS mode ...)  etc.)
clang: error: invalid version number in '-mmacosx-version-min='
clang: error: invalid version number in '-mmacosx-version-min='
clang: error: invalid version number in '-mmacosx-version-min='
make[2]: *** [debug/device.o] Error 1
make[2]: *** [debug/main.o] Error 1
make[2]: *** [debug/main.o] Error 1
make[1]: *** [debug] Error 2
make[1]: *** [debug] Error 2
make[1]: *** [debug] Error 2
make: *** [sub-src-ckb-daemon-make_first] Error 2
make: *** Waiting for unfinished jobs....
make: *** [sub-src-ckb-ripple-make_first] Error 2
make: *** [sub-src-ckb-wave-make_first] Error 2
rebindwidget.ui: Warning: The name 'layoutWidget' (QWidget) is already in use, defaulting to 'layoutWidget2'.
In file included from mainwindow.cpp:2:
In file included from ./kbmanager.h:8:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from kbwidget.cpp:7:
In file included from ./fwupgradedialog.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from main.cpp:1:
In file included from ./mainwindow.h:9:
In file included from ./kbwidget.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
mainwindow.cpp:257:64: warning: unused parameter 'reason' [-Wunused-parameter]
void MainWindow::iconClicked(QSystemTrayIcon::ActivationReason reason){
                                                               ^
kbwidget.cpp:168:91: warning: unused parameter 'previous' [-Wunused-parameter]
void KbWidget::on_modesList_currentItemChanged(QListWidgetItem *current, QListWidgetItem *previous){
                                                                                          ^
2 warnings generated.
In file included from settingswidget.cpp:5:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
settingswidget.cpp:143:47: warning: unused parameter 'index' [-Wunused-parameter]
void SettingsWidget::on_capsBox_activated(int index){
                                              ^
settingswidget.cpp:147:48: warning: unused parameter 'index' [-Wunused-parameter]
void SettingsWidget::on_shiftBox_activated(int index){
                                               ^
settingswidget.cpp:151:47: warning: unused parameter 'index' [-Wunused-parameter]
void SettingsWidget::on_ctrlBox_activated(int index){
                                              ^
settingswidget.cpp:155:46: warning: unused parameter 'index' [-Wunused-parameter]
void SettingsWidget::on_altBox_activated(int index){
                                             ^
settingswidget.cpp:159:46: warning: unused parameter 'index' [-Wunused-parameter]
void SettingsWidget::on_winBox_activated(int index){
                                             ^
3 warnings generated.
3 warnings generated.
7 warnings generated.
In file included from kblight.cpp:5:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from kbprofile.cpp:1:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
kbanimwidget.cpp:151:94: warning: unused parameter 'previous' [-Wunused-parameter]
void KbAnimWidget::on_animList_currentItemChanged(QListWidgetItem *current, QListWidgetItem *previous){
                                                                                             ^
2 warnings generated.
kbanim.cpp:333:32: warning: unused parameter 'bg' [-Wunused-parameter]
static float blendNormal(float bg, float fg){
                               ^
1 warning generated.
animadddialog.cpp:28:46: warning: unused parameter 'index' [-Wunused-parameter]
void AnimAddDialog::on_animBox_activated(int index){
                                             ^
1 warning generated.
1 warning generated.
animsettingdialog.cpp:487:57: warning: unused parameter 'arg1' [-Wunused-parameter]
void AnimSettingDialog::on_delayBox_valueChanged(double arg1){
                                                        ^
animsettingdialog.cpp:491:58: warning: unused parameter 'arg1' [-Wunused-parameter]
void AnimSettingDialog::on_repeatBox_valueChanged(double arg1){
                                                         ^
animsettingdialog.cpp:495:59: warning: unused parameter 'arg1' [-Wunused-parameter]
void AnimSettingDialog::on_kpDelayBox_valueChanged(double arg1){
                                                          ^
animsettingdialog.cpp:499:60: warning: unused parameter 'arg1' [-Wunused-parameter]
void AnimSettingDialog::on_kpRepeatBox_valueChanged(double arg1){
                                                           ^
animsettingdialog.cpp:503:58: warning: unused parameter 'arg1' [-Wunused-parameter]
void AnimSettingDialog::on_kpReleaseBox_stateChanged(int arg1){
                                                         ^
gradientdialog.cpp:174:98: warning: unused parameter 'previous' [-Wunused-parameter]
void GradientDialog::on_presetList_currentItemChanged(QListWidgetItem *current, QListWidgetItem *previous){
                                                                                                 ^
gradientdialog.cpp:240:54: warning: unused parameter 'arg1' [-Wunused-parameter]
void GradientDialog::on_stopOpacity_valueChanged(int arg1){
                                                     ^
5 warnings generated.
In file included from kbmode.cpp:1:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from kb.cpp:6:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
rlistwidget.cpp:54:43: warning: unused parameter 'item' [-Wunused-parameter]
void RListWidget::change(QListWidgetItem* item){
                                          ^
1 warning generated.
In file included from kbprofiledialog.cpp:2:
In file included from ./kbprofiledialog.h:5:
In file included from ./kbwidget.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
kbprofiledialog.cpp:39:100: warning: unused parameter 'previous' [-Wunused-parameter]
void KbProfileDialog::on_profileList_currentItemChanged(QListWidgetItem *current, QListWidgetItem *previous){
                                                                                                   ^
In file included from keywidget.cpp:7:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
3 warnings generated.
In file included from kbbindwidget.cpp:2:
In file included from ./kbbindwidget.h:5:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from kbbind.cpp:4:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from rebindwidget.cpp:2:
In file included from ./rebindwidget.h:5:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from modeselectdialog.cpp:1:
In file included from ./modeselectdialog.h:5:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
rebindwidget.cpp:850:48: warning: unused parameter 'checked' [-Wunused-parameter]
void RebindWidget::on_rb_delay_no_toggled(bool checked)
                                               ^
rebindwidget.cpp:862:53: warning: unused parameter 'checked' [-Wunused-parameter]
void RebindWidget::on_rb_delay_asTyped_toggled(bool checked)
                                                    ^
rebindwidget.cpp:873:53: warning: unused parameter 'checked' [-Wunused-parameter]
void RebindWidget::on_rb_delay_default_toggled(bool checked)
                                                    ^
2 warnings generated.
2 warnings generated.
5 warnings generated.
In file included from kbfirmware.cpp:1:
In file included from ./kbfirmware.h:4:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from fwupgradedialog.cpp:3:
In file included from ./fwupgradedialog.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from kbperf.cpp:2:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
kbperf.cpp:330:27: warning: comparison of constant 8 with expression of type 'KbPerf::indicator' is always false [-Wtautological-constant-out-of-range-compare]
    if(index < 0 || index >= I_COUNT)
                    ~~~~~ ^  ~~~~~~~
kbperf.cpp:345:27: warning: comparison of constant 8 with expression of type 'KbPerf::indicator' is always false [-Wtautological-constant-out-of-range-compare]
    if(index < 0 || index >= I_COUNT)
                    ~~~~~ ^  ~~~~~~~
2 warnings generated.
2 warnings generated.
4 warnings generated.
In file included from keyaction.cpp:2:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from mperfwidget.cpp:1:
In file included from ./mperfwidget.h:11:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
mperfwidget.cpp:81:36: warning: unused parameter 'index' [-Wunused-parameter]
void MPerfWidget::colorClicked(int index){
                                   ^
In file included from kperfwidget.cpp:1:
In file included from ./kperfwidget.h:9:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from layoutdialog.cpp:2:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
3 warnings generated.
2 warnings generated.
In file included from kbmanager.cpp:1:
In file included from ./kbmanager.h:8:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from extrasettingswidget.cpp:3:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from release/moc_kbwidget.cpp:9:
In file included from release/../kbwidget.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_mainwindow.cpp:9:
In file included from release/../mainwindow.h:9:
In file included from ./kbwidget.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from release/moc_kbprofile.cpp:9:
In file included from release/../kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from release/moc_kbmode.cpp:9:
In file included from release/../kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from release/moc_kb.cpp:9:
In file included from release/../kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from release/moc_kbprofiledialog.cpp:9:
In file included from release/../kbprofiledialog.h:5:
In file included from ./kbwidget.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_kbbindwidget.cpp:9:
In file included from release/../kbbindwidget.h:5:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from release/moc_kbbind.cpp:9:
In file included from release/../kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from release/moc_rebindwidget.cpp:9:
In file included from release/../rebindwidget.h:5:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_modeselectdialog.cpp:9:
In file included from release/../modeselectdialog.h:5:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from release/moc_kbfirmware.cpp:9:
In file included from release/../kbfirmware.h:4:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_fwupgradedialog.cpp:9:
In file included from release/../fwupgradedialog.h:7:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
In file included from release/moc_keyaction.cpp:9:
release/../keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
release/../keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from release/moc_mperfwidget.cpp:9:
In file included from release/../mperfwidget.h:11:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
In file included from release/moc_kperfwidget.cpp:9:
In file included from release/../kperfwidget.h:9:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
2 warnings generated.
In file included from release/moc_kbmanager.cpp:9:
In file included from release/../kbmanager.h:8:
In file included from ./kb.h:7:
In file included from ./kbprofile.h:9:
In file included from ./kbmode.h:6:
In file included from ./kbbind.h:10:
./keyaction.h:185:44: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline void operator=(const KeyAction& rhs) {}
                                           ^
./keyaction.h:186:39: warning: unused parameter 'rhs' [-Wunused-parameter]
    inline KeyAction(const KeyAction& rhs) : QObject() {}
                                      ^
2 warnings generated.
You should upload:
- Linux: `ckb-dev-detect-report.gz` is enough
- macOS:

    ```

## What is the program's current behavior?
nothing
## What is the expected behavior of the program?
something
## Any other notes & comments?
I have looked at other problems similar to mine but none have an answer that also works for my case.
---

# Something else

<sub><sup>if your issue is about something else, try your best to describe it here, otherwise leave empty</sup></sub>

**Comment by ghost** [comment] 2017-07-08 22:10
Duplicate of #232.

**Closed as completed by ghost** 2017-07-08 22:10 UTC
Labels: duplicate
