### ISSUE TITLE
Macro recording stop button doesnt work once recording Corsair Sabre

### ISSUE THREAD

**Issue by Strum355** [mattanger/ckb-next#288] opened 2017-08-29 22:01 UTC
# Bug report

- [x] Yes
- [ ] No

### Source

Download zip from master branch. Unzip, `sudo ./quickinstall`

### Branch

_master_ 

## Logs & crash reports

- Linux: `ckb-dev-detect-report.gz` uploaded

## What is the program's current behavior?

In Macro tab for Corsair Sabre, when i click Start, the Stop button does not work, requiring me to kill ckb for it to stop recording, which however wipes what has been recorded.

## What would you like it to do instead?

For the stop button to actually stop recording the macro so i can bind Alt+Tab to my mouse button. 
[ckb-dev-detect-report.gz](https://github.com/mattanger/ckb-next/files/1261861/ckb-dev-detect-report.gz)

**Comment by Anonrate** [comment] 2017-09-16 22:24
I confirm this happens with the Scimitar Pro RGB as well.  When I had the Regular Scimitar RGB as well, it did the samething.  Not sure if it still does as I don't have that mouse anymore.  I've got the updated one.

I believe this is a duplicate of #121

**Closed as completed** 2018-01-21 21:48 UTC
Labels: duplicate, migration
