### ISSUE TITLE
Corsair Strafe RGB Crashes on picking color

### ISSUE THREAD

**Issue by pseudoArchaea** [mattanger/ckb-next#142] opened 2017-04-09 23:40 UTC
Arch Linux
Using this version of ckb-next 26f90f3e5296ad40b85e87bd091d606aeb3d2827

Steps to reproduce - click on New Mode button, pick any key and click on the color selection button - it crashes with this output.

https://pastebin.com/raw/eD6KP1uV

**Comment by ghost** [comment] 2017-04-09 23:43
Please, read the README: https://github.com/mattanger/ckb-next#linux
Duplicate of #116, #70, #51, ccMSC/ckb#500, ccMSC/ckb#461

**Closed as completed by ghost** 2017-04-09 23:43 UTC
Labels: duplicate
