### ISSUE TITLE
Mouse go to top left on click and hold Corsair Sabre

### ISSUE THREAD

**Issue by AlfaceVerde** [mattanger/ckb-next#274] opened 2017-08-07 15:49 UTC
My mouse jump to the very top left corner of my screen when I click and hold.

I don't know why this problem occurs. Sometimes changing my USB ports helps, sometimes it does not help.

I noticed some people was having the same problems, if I left my mouse unplugged for a while and then replugged it would function correctly at a higher percentage rate. 

My Hardware:

 Mac mini
 Macmini7,1
 Intel Core i5
 2,8 GHz
 8 GBI ram,  am using OS X 10.11.6 
Mouse: Corsair Sabre RGB
Keyboard: Corsair K65 RGB Rapid Fire

No other USB devices have issues. I saw some other peoples having the same problem, but no resolution came to us, if anyone know how to solve this, i will be so glad, tnks!

**Comment by ghost** [comment] 2017-08-07 17:29
Duplicate of #93.

**Closed as completed by ghost** 2017-08-07 17:29 UTC
Labels: duplicate
