### ISSUE TITLE
K65 RGB RAPIDFIRE problem with (SHIFT|COMMAND|OPTION)+mouse click

### ISSUE THREAD

**Issue by mrgaolei** [mattanger/ckb-next#112] opened 2017-03-13 03:37 UTC
Every thing seems OK,

But, when I press shift + click(I want to select multi-line text), it doesn't selected.

And also, I press cmd + click in Safari (I want open link in new tab), it doesn't open.

In MacBook Pro's keyboard, it can be.

**Comment by ghost** [comment] 2017-03-13 05:20
Duplicate of #29.

**Closed as completed by ghost** 2017-03-13 05:20 UTC
Labels: duplicate
