### ISSUE TITLE
Modes Disappeared 

### ISSUE THREAD

**Issue by sam-gurdus** [mattanger/ckb-next#128] opened 2017-03-29 02:36 UTC
When I rebooted/crashed my computer I lost all of my modes in ckb. These had some pretty awesome animations/colors and all my bindings. I was wondering if not a fix, is there was any way I could recover them. I am using macOS Sierra

**Comment by ghost** [comment] 2017-03-29 03:04
Try #90.

**Comment by sam-gurdus** [comment] 2017-03-29 03:48
How would I go about installing this 'patch?'

**Comment by ghost** [comment] 2017-03-29 07:51
As with https://github.com/mattanger/ckb-next/issues/29#issuecomment-289412693.

**Comment by tatokis** [comment] 2017-04-25 11:11
Closing as duplicate of #83.

**Closed as completed by tatokis** 2017-04-25 11:11 UTC
Labels: duplicate
